#!/usr/bin/env node
// tools/generate-thema.js
//
// Reads EDItEUR's Thema JSON and emits Resources/onix-thema.js: every Thema
// code with its English heading, one Map per ONIX subject scheme.
//
// EDItEUR publishes the JSON at
//   https://www.editeur.org/files/Thema/<version>/v<version>_en/<date>_Thema_v<version>_en.json
// and we keep the latest committed at tools/data/thema-codes.json.
//
// Thema is one code list in seven ONIX schemes (List 27): the subject
// categories, whose codes start with a letter, are scheme 93, and each of
// the six qualifier families, whose codes start with a digit, is a scheme
// of its own — 1 place (94), 2 language (95), 3 time period (96),
// 4 educational purpose (97), 5 interest age (98), 6 style (99).
//
// Usage:
//   node tools/generate-thema.js
//   node tools/generate-thema.js --json=<path>

"use strict";

const fs = require("fs");
const path = require("path");

const JSON_PATH = parseArg("--json=") || path.join(__dirname, "data", "thema-codes.json");
const OUT_PATH = path.join(__dirname, "..", "Resources", "onix-thema.js");

const SCHEME_BY_FIRST_CHARACTER = { 1: "94", 2: "95", 3: "96", 4: "97", 5: "98", 6: "99" };

function parseArg(prefix) {
  const argument = process.argv.find((a) => a.startsWith(prefix));
  return argument ? argument.slice(prefix.length) : null;
}

function schemeOf(code) {
  const scheme = /^[A-Z]/.test(code) ? "93" : SCHEME_BY_FIRST_CHARACTER[code[0]];
  if (!scheme) throw new Error(`Thema code ${code} belongs to no ONIX scheme`);
  return scheme;
}

function readCodeList(file) {
  const text = fs.readFileSync(file, "utf8").replace(/^\uFEFF/, "");
  const list = JSON.parse(text).CodeList;
  if (!list || !list.ThemaCodes || !Array.isArray(list.ThemaCodes.Code)) {
    throw new Error(`${file} is not a Thema code list`);
  }
  return list;
}

function groupBySchemes(codes) {
  const schemes = {};
  const seen = new Set();
  for (const entry of codes) {
    const code = String(entry.CodeValue).trim();
    const heading = String(entry.CodeDescription).trim();
    if (/[\t\n]/.test(code + heading)) throw new Error(`Thema code ${code} carries a tab or newline`);
    if (!code || !heading) throw new Error(`Thema entry without a code or heading: ${JSON.stringify(entry)}`);
    if (seen.has(code)) throw new Error(`Thema code ${code} appears twice`);
    seen.add(code);
    const scheme = schemeOf(code);
    (schemes[scheme] = schemes[scheme] || []).push([code, heading]);
  }
  return schemes;
}

function isoDate(yyyymmdd) {
  const digits = String(yyyymmdd);
  return `${digits.slice(0, 4)}-${digits.slice(4, 6)}-${digits.slice(6, 8)}`;
}

// Each scheme is one string of "code<TAB>heading" lines, split into a Map
// at load. Written as a Map literal, the punctuation and indentation of
// 9,187 entries came to a third of the file.
function render(list, schemes) {
  const version = String(list.IssueNumber);
  const lastUpdated = isoDate(list.LastUpdated["#text"]);
  const lines = [
    "// onix-thema.js — AUTO-GENERATED. Do not edit by hand.",
    "//",
    `// Generated by tools/generate-thema.js from EDItEUR's Thema ${version} code list`,
    `// (English, last updated ${lastUpdated}). One Map<code, heading> per ONIX`,
    "// subject scheme, 93 to 99, in EDItEUR order, each written as",
    "// \"code<TAB>heading\" lines.",
    "",
    "(function () {",
    "  const packed = {",
  ];
  for (const scheme of Object.keys(schemes).sort()) {
    const text = schemes[scheme].map(([code, heading]) => `${code}\t${heading}`).join("\n");
    lines.push(`    ${JSON.stringify(scheme)}: ${JSON.stringify(text)},`);
  }
  lines.push(
    "  };",
    "  const schemes = {};",
    "  for (const scheme of Object.keys(packed)) {",
    "    schemes[scheme] = new Map(packed[scheme].split(\"\\n\").map((line) => line.split(\"\\t\")));",
    "  }",
    "  window.OnixViewerThema = {",
    `    version: ${JSON.stringify(version)},`,
    `    lastUpdated: ${JSON.stringify(lastUpdated)},`,
    "    schemes,",
    "  };",
    "})();",
    "",
  );
  return lines.join("\n");
}

function main() {
  const list = readCodeList(JSON_PATH);
  const schemes = groupBySchemes(list.ThemaCodes.Code);
  fs.writeFileSync(OUT_PATH, render(list, schemes));
  const counts = Object.keys(schemes).sort().map((s) => `${s}: ${schemes[s].length}`).join(", ");
  console.log(`Wrote ${path.relative(process.cwd(), OUT_PATH)} — Thema ${list.IssueNumber}, ${counts}`);
}

main();
